config/routes.rb
Rails.application.routes.draw do
  root 'contacts#index'
  resources :contacts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def index

		@contacts = Contact.all

	end

	def new 
		@contact = Contact.new
	end

	def create
		Contact.create(contact_params)
		redirect_to root_path

	end

	def contact_params
		params.require(:contact).permit(:name, :description, :address)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/index.html.erb
<div class="title">
<h1>Challenge Quiz #2</h1>
</div>


<div class="col-10 offset-1 text-center"> 
<%= link_to 'Create New Contact', new_contact_path(@contact), class: 'btn btn-primary' %>
</div>

<% @contacts.each do |contact| %>

<div class="booyah-box col-10 offset-1">
	
  

	<h1><%= contact.name %></h1>
	<i><%= contact.address %></i><br /><br />
	<p><%= contact.description %></p><br />
</div>
<% end %>

app/views/contacts/new.html.erb
<div class="booyah-box col-10 offset-1">
<h1>Enter your information</h1>
<%= simple_form_for @contact do |f| %>
	<%= f.input :name %>
	<%= f.input :address %>
	<%= f.input :description %>
	<%= f.submit 'Create' %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Challenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>